### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [Exxplosion/Sirius_2022#1]
1) Первое задание зачтено.

2) По поводу второго задания. Условие, похоже, неверное, то есть оно, по идее, проверяет, пересекается ли отрезок с прямой, а не с лучом (но вообще когда пишите подобную формулу, лучше добавить комментарии, чтобы было понятно, как она олучается, и не нужно было её получать самомтоятельно). Кроме того, нет проверки принадлежности точки границе. Ещё лучше сделать функцию, которыя проверяет принадлежность точки многоугольнику, а не делать это в main, и вынести функцию в отдельный файл. В общем, требкется некоторая доработку (в первую очередь перепроверить пересечение луча и отрезка и добавить проверку принадлежности стороне).

3) Ввод данных и обработка ошибок не ищменены относительно моих реализаций, поэтому третье задание пока не зачтено.

**Comment by Exxplosion** [comment]
Здравствуйте!! Я обновил и залил версию которая уже претендует на решение.
Возникло несколько вопросов (а именно, я не понял как определять макрос
дебаг в процессе сборки проекта ((я подумал эта строчка должна это сделать)
-DCMAKE_BUILD_TYPE=Debug, ) или надо в самой программе ее определять (но
это как-то по другому мне казалось должно работать). И еще немного про код
который мы писали на лекции, который открываает и считывает файл, я заметил
что мы его забыли закрыть (его же нужно закрыть, правильно?) И еще хотел
добавить про сравнение даблов, посмотрите так ли я сделал, может как-то
иначе мо(ну)жно. Кстати тупо сравнивать "==" тоже получалось успешно, даже
когда точки лежали почти к границы (но конечно я понимаю что лучше так не
делать).

**Comment by dzheltkov** [comment]
Да, конфигурация с помощью команды cmake -DCMAKE_BUILD_TYPE=Debug .. определяет, в том  числе, макрос DEBUG при сборке, но у вас неправильно в коде сделана проверка на наличие этого макроса. Вы используете #if**n**def DEBUG, что означает if **not** defined DEBUG, то есть соответствующий код будет включён в программу когда макрос DEBUG **не** определён. Для того, чтобы код включался, когда макрос определён, нужно использовать #ifdef DEBUG

Да, всё верно, в случае C чтения из файла закрывать файл необходимо, то есть в коде допущена ошибка, нужно исправить, спасибо.
В случае C++ при выходе из области видимости переменной типа std::fstream (std::ifstream и std::ofstream в том числе) переменная уничтожается, так как это класс (можете считать пока, что структура), то вызывается деструктор, который, в том числе, закрывает файл, если он открыт. То есть в C++ случае можно закрыть файл с помощью специальной функции самостоятельно, но делать это необязательно.

Про сравнение double -  она у вас сделана не вполне правильно: то есть вы ожидаете, при проверки этого условия, что t1 и t2 по модулю не превосходят единицы, и, более того, погрешность их вычиления будет относительно 1 в большинстве случаев, поэтому действительно можно использовать абсолютный, а не относительный порог (на самом деле, не вполне так, если pX[i + 1] - pX[i] близко к 0 относительно модуля pX[i] и pX[i + 1], или pY[i + 1] - pY[i] близко к 0 относительно  pY[i] и pY[i + 1], то t1 и t2 будут посчитаны с низкой относительной точностью, и порог нужно повышать, но это проблема устойчивости используемого алгоритма, решая данную задачу более устойчивым способом можно от этой проблемы практически избавиться).
Но порог у вас выбран неверно -- если у вас действительно t1 и t2 по модулю около 1, то условие может быть фактически выполнено только тогда, когда t1 == t2. Чтобы сделать условие правильным, нужно умножить epsilon на некоторую константу, связанную с количеством произведённых операций и числом обучловленности задачи (чтобы не иметь проблем с числом обусловленности и не оценивать его, обычно сравнивают невязки, а не решения, на паре сегодня покажу, если будет время, если нет -- то в перерыве). То есть, нужно сравнивать не с epsilon, а с 10 или 100 epsilon.

Ещё я всё же не вполне верю в вашу формулу проверки пересечения отрезков, если не сложно, поясните её комментариями в коде (или подойдите в перерыве).

По поводу обработки ошибок -- перечислимый тип вижу, с ним всё хорошо, но нужно ещё конвертацию аргументов и чтение из файла переделать так, чтобы использовались или только C функции ввода-вывода, или только С++ функции.

**Comment by Exxplosion** [comment]
Добрый вечер, не могли бы посмотреть задачу 4. С изображением не сделал (довольно долго разбираться в том репозиторим в комментариях Сурова (я начал смотреть, но решил что много времени на это уйдет...)).  Сделал, пока, правда, для случая M > N, но другой случай делается несложно (моё решение немного "нестандартное"...). Так-то алгоритм по предполагаемой матрице $M \times N$ (M>N) с весами в каждом элементе находит требуемый путь от $х_s$ к $x_f$. Массив dumb_path нужен для отрисоки, но далее нигде не используется.

**Comment by dzheltkov** [comment]
Добрый день!
В целом алгоритм правильный, несколько замечаний:
1) В репозитории есть ряд файлов, которых там быть не должно (папка build, откомпилированный файлы, файл .gdb_history, папка .vscode).
2) Не стоит создавать внутри функции указатель на std::vector (в целот не стоит так делать не только с std::vector) и возвращать ссылку на полученный объект, это приведёт к утечке памяти (можете проверит с помощью valgrind). Если не понимаете почему так, то подойдите сегодня в перерыве, или же я завтра на паре объясню.
Вместо этого создавайте просто временный объект (то есть без new) и возвращайте не ссылку. Компилятор это соптимизирует.
3) По предыдущим заданиям. Второе я вам зачёл, а вот при обработки ошибок у вас до сих пор (по крайней мере тот код, что в репозитории) использует как С, так и С++ ввод / вывод для обработки параметров запуска и чтения файла.
Нужно каким-то одним из способов.
4) Для того, чтобы 4-е задание было полностью зачтено нужно исправить указанные и доразобаться с загрузкой/сохранением PNG.

**Comment by Exxplosion** [comment]
Доброй ночи!!!

* Доработал с png, можете посмотреть мой путь на картинке out.png в build (да, я оставил эту папку, т.к. я не разобрался с тем (просто уже почти 3 a.m.... ) как сохранить картинку в нужной папке и почему строчка `*/build/*` в .gitignore не работает как хочется...). 
_Да, они немного не совпадают, тем не менее моя "линия" движется по черной области (то есть по условию энергоэффективно), может быть, тут есть несколько решений..._

* Я, к сожалению, только сейчас прочитал полностью Ваше issue (в почте отображалось не всё или я забыл) и второй пункт не сделал, утечки памяти действительно есть в текущей программе (тем не менее она работает...), так же столкнулся с каким-то странным поведением, при изменении константы в классе дейкстра (`const uint32_t INF_` ) в 10 раз (с 45.000 до 450.000 (максимальное значение uint32 конечно больше...) возникает ошибка сегментации (я пытался понять почему, но даже с помощью valgrind всё равно не смог...)

* 3-й пункт по 2-й задаче не полностью понял, нужно использовать чтение из файла только одним (С или С++) способом, а обработку ошибок сделать через `try/catch`?

**Comment by dzheltkov** [comment]
- До начала пар, видимо, не успею достаточно подробно посмотреть ваш код, так что по поводу другой линии, просто ли это другой путь, или же ошибка, и по поводу ошибки сегментации пока сказать ничего не могу. Тем не менее, ошибку приводящую к ошибке сегментации а также утечку памяти нужно исправить.

- По поводу второй задачи. `try / catch` не обязательны, но у вас при парсинге аргументов командной строки и при чтении из файл используется как `sscanf / fscanf` (то есть C функции работы с вводом-выводом), так и `istringstream / ifstream` (то есть C++ классы для работы с вводом / выводом). Так делал я в примере, выложенном в репозитории, чтобы показать, как это делается одним и другим способом. Для зачёта третьего задания я просил изменить этот код так, чтобы использовался только один (любой на ваш выбор) подход - либо `sscanf / fscanf`, либо `ifstream / istringstream`.

**Comment by Exxplosion** [comment]
Здравствуйте, удалось исправить ошибку с "неправильным чтением байтов" вне массива, но всё же под валгриндом какие-то единицы байт утекают... На решение это не влияет, кстати, путь который нарисован у автора неправильный, в том плане, что там есть "движения" по диагонали.

**Comment by dzheltkov** [comment]
Проблема с утечкой памяти всё та же, что описана здесь:

> 2. Не стоит создавать внутри функции указатель на std::vector (в целот не стоит так делать не только с std::vector) и возвращать ссылку на полученный объект, это приведёт к утечке памяти (можете проверит с помощью valgrind). Если не понимаете почему так, то подойдите сегодня в перерыве, или же я завтра на паре объясню.
>    Вместо этого создавайте просто временный объект (то есть без new) и возвращайте не ссылку. Компилятор это соптимизирует.

То есть у вас в коде (dijkstra.h 26-43 строки, dijkstra.cpp 208-222 строки) есть конструкции вида:
```
std::vector<uint32_t>& f()
{
std::vector<uint32_t>* p = new std::vector<uint32_t>;
...
return *p;
}
```
При уничтожении ссылки память не очищается (и это правильно), поэтому у вас утечка памяти.
Из функции НЕЛЬЗЯ возвращать ссылку на временный объект (если будет совсем так, то компилятор не позволит), в том числе создавать указатель и возвращать разыменованный объект. Если бы вы этот указатель сохраняли в какой-то невременный объект, который потом бы его очищал -- тогда так можно было бы делать. Но тогда обычно проще использовать не указатель, а невременный объект такого типа (кстати, в dijkstra.cpp вообще непонятно, зачем вы ак делаете, у вас есть объект-поле класса и вместо создания нового объекта можно было использовать поле класса и вернуть ссылку на него).
Если же возможности использовать невременный объект нет (как в случае, который у вас в dijkstra.h), то создаёе временный объект (а не указатель на него) и возвращаете копированием, компилятор это копирование соптимизирует, реально его происходить не будет (в Debug сборке будет, но и ладно).
То есть, следовало писать так:
```
std::vector<uint32_t> f()
{
std::vector<uint32_t> p;
...
return p;
}
```

**Comment by Exxplosion** [comment]
доброй ночи, посмотрите пожалуйста задание 6,
https://github.com/Exxplosion/Sirius_2022/tree/master/C%2B%2B/task_6 ,
основная функциональность есть, осталось написать matvec для COO, но нужно
спать, завтра к первой, очень много времени потратил на разрешения ошибок
при наследовании и в целом на идеалогию наследования. и, если можно,
пожалуйста зачесть задачу 3 и 5 (ну и 4), просто мне кажется, что эта
задача и задача на алгоритм дейкстры будет "побольше" и в каком-то смысле
включает задачу на односвязный список... но если и не прав, то вот например
реализация двухсвязного списка на С который я делал 4 года назад на втором
курсе...
https://github.com/Exxplosion/track.mail-Introduction_to_Industrial_Programming_C/tree/master/List_tree_akin/list_dvyh
, тут даже картинка классная :
https://github.com/Exxplosion/track.mail-Introduction_to_Industrial_Programming_C/blob/master/List_tree_akin/list_dvyh/heh.png
. не знаю когда кину задачу 7, мне кажется ближе к зачету......
.
