### ISSUE TITLE
Задание 6

### ISSUE THREAD

**Issue by dzheltkov** [Exxplosion/Sirius_2022#2]
Задание зачтено (хотя в main пока нет использования динамического полиморфизма).
Попозже (в среду) выложу пример, как можно было всё сделать.

Задания 3-5 тоже зачту.

**Comment by Exxplosion** [comment]
Здраствуйте, посмотрите задание 7.... Скажу сразу, оно не работает, невязка стремится к бесконечности, если я не в каком-то эпсилон в начальном приближении от решения (эпсилон ~ 1).... Немного по идее, в этой задаче требуется определить функцию умножения матрицу на транспонированую, для 4-х классов это как-то жеско... Поэтому я решил ~~этого не делать~~, а решать СЛУ сразу для симметричной полож. определенной матрицы. Для легчайшого примера 
А = [[1,0], [0, 1]], b = [1, 1], работает, но если изменить в А 1 на 20, то уже нет.... Не знаю что не так, реально много времени потратил, перепроверял реализацию много раз, уже начал писать скрипт на питоне чтобы просто сравнивать значения программ. Тем не менее, шаблоны работают и динамический полиморфизм тоже (функция CGNE принимает абстрактный класс Matrix). Я допишу. но уже к завтрашнему дню не успею, начался следующий курс (в котором просят реализовать статью...). Так же возник небольшой вопрос, не знаю как его правильно сформулировать, допустим `<template class T>`, где T это, допустим std::vector<float>. Так вот, как мне передавать в функцию шаблон НЕ только Т (который "равен" std::vector<float>), но и сам тип вектора, то есть <float>?

**Comment by dzheltkov** [comment]
Нет, в этой задаче НЕ требуется определить умножение матрицы на транспонированную.
Эта операция плохая со всех сторон (для плотных матриц она сложнее решения системы, для разреженных -- увеличивает количество ненулей, поэтому увеличивается объём требуемой памяти и сложность умножения на вектор).
Просто на каждой итерации происходит сначала матрицы на вектор, а потом транспонированной матрицы на вектор.

Ошибки сходу не вижу, хотя она, очевидно, есть.

Задание зачту.

Шаблон для вектора делается так:
`template <template class vector_type, class data_type>`
Далее где необходимо используете `vector_type<data_type>`.
